### ISSUE TITLE
[Login] Login error don't return enough data.

### ISSUE THREAD

**Issue by cunbidun** [Saakshaat/projectory#15]
**Describe the bug**
When user without profile login, the server will return error to notify client about it. However, the client doesn't return a `uid` and `credentials` for profile creation process.

**Comment by Saakshaat** [comment]
Fixed in d6a713053785de4818f360658605065bb268d2f3
Now the server returns a `406` response status with the required data for creating a profile.

On the client application, check if the login request returns `406`, if so redirect them to the profile creation page and save the response body for the client's next request.
